name: Continuous

on: [push]

jobs:

  mac:
    strategy:
      matrix:
        cfg: [
              # need clang 16 min for C++20 support
              # macos-13 for intel macos runner
              # macos-14 for apple silicon runner
              {os: macos-13, cxx: /opt/homebrew/opt/llvm@20/bin/clang++},
              {os: macos-14, cxx: /opt/homebrew/opt/llvm@20/bin/clang++},]
        config: [Release, Debug]
    
    runs-on:  ${{ matrix.cfg.os }}

    env:
      CXX: ${{ matrix.cfg.cxx }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 4.2.3

    - name: Install Clang 20 (macOS)
      run: |
        brew update
        brew install llvm@20
        brew install glfw

    - name: Configure CMake
      # Deactivate wayland for the moment but maybe use
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DGLFW_BUILD_WAYLAND=OFF

    - name: CMake Build
      run: cmake --build build --parallel

    - name: Run WebGPU app mac os
      run: ./build/webgpu_cpp_minimal --ci-test

    - name: Create archive
      if: ${{ github.ref_type == 'tag' }}
      run: tar -czvf webgpu_template_${{ matrix.cfg.os }}.tar.gz build/*

    - name: Deploy
      uses: xresloader/upload-to-github-release@v1
      with:
        tags: true
        draft: false
        file: webgpu_template_${{ matrix.cfg.os }}.tar.gz
        overwrite: false
        update_latest_release: true
        verbose: true

  linux:
    strategy:
      matrix:
        cfg: [{os: ubuntu-latest, cxx: g++-13},
              # get clang 16 ! because we need C++20 support
              {os: macos-latest, cxx: /opt/homebrew/opt/llvm@20/bin/clang++}]
        config: [Release, Debug]

    runs-on:  ${{ matrix.cfg.os }}

    env:
      CXX: ${{ matrix.cfg.cxx }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 4.2.3

    - name: Install Clang 20 (macOS)
      if: matrix.cfg.os == 'macos-latest'
      run: |
        brew update
        brew install llvm@20
        brew install glfw

    - name: Install dependencies
      if: matrix.cfg.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        # Install GLFW development packages
        sudo apt-get install -y \
          libx11-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxcursor-dev \
          libxi-dev \
          libxext-dev \
          libwayland-dev \
          wayland-protocols \
          libxkbcommon-dev \

    - name: Configure CMake
      
      #     sudo apt-get update
      # sudo apt-get install -y \
      #   libglfw3-dev \
      # Deactivate wayland for the moment but maybe use
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DGLFW_BUILD_WAYLAND=OFF

    - name: CMake Build
      run: cmake --build build --parallel

    - name: Install GLFW runtime dependencies
      if: matrix.cfg.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xvfb \
          libx11-6 \
          libxrandr2 \
          libxinerama1 \
          libxcursor1 \
          libxi6 \
          mesa-vulkan-drivers

    - name: Run WebGPU app x11 server
      if: matrix.cfg.os == 'ubuntu-latest'
      run: |
        xvfb-run -a \
          --server-args="-screen 0 1280x720x24" \
          ./build/webgpu_cpp_minimal --ci-test

    - name: Run WebGPU app mac os
      if: matrix.cfg.os == 'macos-latest'
      run: ./build/webgpu_cpp_minimal --ci-test

    - name: Create archive
      if: ${{ github.ref_type == 'tag' }}
      run: tar -czvf webgpu_template_${{ matrix.cfg.os }}.tar.gz build/*

    -
      name: Deploy
      uses: xresloader/upload-to-github-release@v1
      with:
        tags: true
        draft: false
        file: webgpu_template_${{ matrix.cfg.os }}.tar.gz
        overwrite: false
        update_latest_release: true
        verbose: true


  windows-msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 4.2.3

    - name: Configure CMake
      run: cmake -B build

    - name: Release build
      run: cmake --build build --parallel --config Release

    - name: Create archive
      if: ${{ github.ref_type == 'tag' }}
      run: Compress-Archive -Path build/Release/* -Destination webgpu_template_win.zip

    -
      name: Deploy
      uses: xresloader/upload-to-github-release@v1
      with:
        tags: true
        draft: false
        file: webgpu_template_win.zip
        overwrite: false
        update_latest_release: true
        verbose: true